# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23bedd7c1e9bf5ac9714901233fd3dddb5de8f03ad1a347e127b04ade1bc2020405bf783766ed2b70b8b2406299bb6e4c60ffd1852e33159ccdc6b201b4ef76d

test:
  secret_key_base: 431c8e294860a3547345147e44ca3b8d2b1a36ef65eb3c3c529c8f94378bb4d5d1731247aada8b156e5acc2dd128ebf03a19b3f4a90f2d7e96c75da0b6dac6af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
